version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: root
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
